### ISSUE TITLE
TB Dipole Model03 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/tb-dipoles#1]
tb-dipoles/model-02/simulation/2016-12-08_TB_Dipole_Model02_Sim_X=-50_50mm_Z=-500_500mm_I=476A.txt

**Comment by xresende** [comment]
new fieldmap with dX = [-85,+85] mm requested.

**Comment by xresende** [comment]
analysis of `2017-08-25_TB_Dipole_Model02_Sim_X=-85_85mm_Z=-500_500mm.txt` done for two situations: 

`1) x0 = 0mm`
`2) x0 = 4.647 mm (centered trajectory sagitta)` 

at current mag excitation, deflection angle is right on nominal value of 15 degrees when x0 = 0 mm. when sagitta is centered, deflection is higher by `0.09%`. multipolos are about the same in both cases

**Comment by xresende** [comment]
when this dipole's model is updated she should consider centering the trajectory sagitta.

**Comment by LuanaVilela** [comment]
Added model-03 fieldmap with current (I=249.1A) adjusted to center the trajectory sagitta.

**Comment by LuanaVilela** [comment]
Model-03 approved.
